# Generated by Django 4.2.6 on 2023-10-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Restaurant_content',
            new_name='restaurant_content',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Restaurant_keyword',
            new_name='restaurant_keyword',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Restaurant_link',
            new_name='restaurant_link',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Restaurant_name',
            new_name='restaurant_name',
        ),
    ]
